---
abstract: 'Some utilities for Org documents'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-OrgUtils
requires:
  Data::Clone: 0
  DateTime: 0
  Lingua::EN::Numbers::Ordinate: 0
  List::MoreUtils: 0
  Log::Any: 0
  Org::Dump: 0
  Org::Parser: 0.26
  Perinci::CmdLine: 0.56
  perl: 5.010001
resources:
  homepage: http://search.cpan.org/dist/App-OrgUtils/
  repository: http://github.com/sharyanto/perl-App-OrgUtils
version: 0.18
